services:
  nolimitflix:
    build:
      context: .
      args:
        NEXT_PUBLIC_MEDIA_URL: ${NEXT_PUBLIC_MEDIA_URL:-https://nolimitflix.com/media}
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL:-https://nolimitflix.com}
        NEXT_PUBLIC_TMDB_API_KEY: ${NEXT_PUBLIC_TMDB_API_KEY}
        NEXT_PUBLIC_GOOGLE_WEB_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_WEB_CLIENT_ID}
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
        NEXT_PUBLIC_CLOUDFRONT_URL: ${NEXT_PUBLIC_CLOUDFRONT_URL:-}
    container_name: nolimitflix
    restart: unless-stopped
    env_file: .env
    ports:
      - "3001:3000"
    volumes:
      - /mnt/data/media/no-limit-flix:/app/media
    networks:
      - shared-net

networks:
  shared-net:
    external: true
