services:
  nolimitflix-worker:
    build:
      context: .
    container_name: nolimitflix-worker
    restart: unless-stopped
    env_file: .env
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - /mnt/data/media/no-limit-flix:/app/media
    networks:
      - shared-net

networks:
  shared-net:
    external: true
