export const MOOD_OPTIONS = [
  { label: 'Thrilling', emoji: '🚀' },
  { label: 'Heartwarming', emoji: '❤️' },
  { label: 'Mind-bending', emoji: '🌀' },
  { label: 'Funny', emoji: '😂' },
  { label: 'Dark', emoji: '🌑' },
  { label: 'Uplifting', emoji: '✨' },
  { label: 'Intense', emoji: '🔥' },
  { label: 'Relaxing', emoji: '🌿' },
  { label: 'Romantic', emoji: '💖' },
  { label: 'Epic', emoji: '⚔️' },
  { label: 'Magical', emoji: '✨' },
  { label: 'Gritty', emoji: '🚬' },
  { label: 'Futuristic', emoji: '🤖' },
  { label: 'Nostalgic', emoji: '🎞️' },
  { label: 'Artistic', emoji: '🎨' },
  { label: 'Spooky', emoji: '👻' },
  { label: 'Mysterious', emoji: '🕵️' },
  { label: 'Action-packed', emoji: '🎦' },
];

export const FEEDBACK_OPTIONS = [
    'Too slow',
    'Too dark',
    'Seen it',
    'Not intense enough',
    'Try something lighter',
];

export const COLLECTIONS = [
    {
        slug: 'mind-benders',
        title: 'Mind Benders',
        description: 'Films that challenge perception and reality',
        count: 24,
        accentColor: '#8B5CF6',
    },
    {
        slug: 'feel-good-classics',
        title: 'Feel-Good Classics',
        description: 'Timeless films that warm the heart',
        count: 32,
        accentColor: '#F43F5E',
    },
    {
        slug: 'visual-masterpieces',
        title: 'Visual Masterpieces',
        description: 'Stunning cinematography and art direction',
        count: 28,
        accentColor: '#D4AF37',
    },
    {
        slug: 'hidden-gems',
        title: 'Hidden Gems',
        description: 'Underrated films worth discovering',
        count: 45,
        accentColor: '#14B8A6',
    },
    {
        slug: 'adrenaline-rush',
        title: 'Adrenaline Rush',
        description: 'High-octane action and thrills',
        count: 36,
        accentColor: '#3B82F6',
    },
    {
        slug: 'slow-cinema',
        title: 'Slow Cinema',
        description: 'Contemplative and meditative experiences',
        count: 18,
        accentColor: '#A7ABB4',
    },
    {
        slug: 'cult-favorites',
        title: 'Cult Favorites',
        description: 'Films with devoted followings',
        count: 41,
        accentColor: '#8B5CF6',
    },
    {
        slug: 'foreign-language',
        title: 'Foreign Language Excellence',
        description: 'International cinema at its finest',
        count: 52,
        accentColor: '#F43F5E',
    },
    {
        slug: 'directors-vision',
        title: "Director's Vision",
        description: 'Auteur-driven masterworks',
        count: 29,
        accentColor: '#D4AF37',
    },
    {
        slug: 'comfort-watches',
        title: 'Comfort Watches',
        description: 'Films you can return to again and again',
        count: 38,
        accentColor: '#14B8A6',
    },
    {
        slug: 'edge-of-your-seat',
        title: 'Edge of Your Seat',
        description: 'Suspense and tension from start to finish',
        count: 33,
        accentColor: '#3B82F6',
    },
    {
        slug: 'animation-excellence',
        title: 'Animation Excellence',
        description: 'The best in animated storytelling',
        count: 27,
        accentColor: '#F43F5E',
    },
];
